### ISSUE TITLE
Ability to renew certs sooner

### ISSUE THREAD

**Issue by NemesisOfNo** [kbareis/letsEncryptJSS#4]
I'm not sure if I'm missing something. It seems you've hard coded in that one cannot renew a Let's Encrypt cert only if the current cert is >60 days. Is there a way to allow this happen sooner?

My current cert expires on a specific day next month. When I run the script today, it exits out stating 
 "Certificates do not need to be updated. Next update needed after 201712XX". This is the day before the cert expires for our JAMF instance.

If I'm to understand correctly, I have a very narrow window to renew my Let's Encrypt certificate? Can there be the option to hard code a specific number of days to allow renewing? I would like the ability to renew my cert every 30 days, but am not comfortable altering the code.

**Comment by kbareis** [comment]
Hi @NemesisOfNo,

The logic that is in the script is a comparison of the modified date of the privkey from Let's Encrypt vs the window that Let's Encrypt allows. Currently, Let's Encrypt only allows certs to be generated for 90 days. In that 90 day window, certs can only be updated between the 60th to 90th day. This is not something that is within my control. If you put the script into cron daily or cron weekly it will automate the script running. Once you have done that, the log should look like:
```
Sun Nov 12 06:47:01: git installed
Sun Nov 12 06:47:01: java installed
Sun Nov 12 06:47:01: keytool installed
Sun Nov 12 06:47:01: openssl installed
Sun Nov 12 06:47:01: Keystore found. JSS appears to be installed.
Sun Nov 12 06:47:01: Lets Encrypt directory already present.
Sun Nov 12 06:47:01: Certificates for v10.jamf.io are already generated. Checking date and time stamps.
Sun Nov 12 06:47:01: Certificates do not need to be updated. Next update needed after 20171123
```
Based on my setup, I have the script set to weekly and my cert expires on 12/24/2017. I would expect the script to run on 11/25/2017 and extend my cert for another 90 days. Does this fit with what you are seeing? If not, please attach a few screenshots of your cert expiration date and your log file in /tmp/letsEncryptConsole.log
