### ISSUE TITLE
Changes in Tomcat can break LetsEncrypt functionality

### ISSUE THREAD

**Issue by sjmosher** [kbareis/letsEncryptJSS#7]
In Jamf 10.7.x, Tomcat upgrades to a newer version and it replaces the existing SSL connector in the conf/server.xml file with a new connector. The default behavior of the JSS installer is to comment out the old connector, which may not point to an accurate TomcatSSLKeystore location such as {catalina.home}. 

To fix, on line 75 and 78, replace matching for `*keystoreFile` and `*keystorePass` with `*certificateKeystoreFile` and `*certificateKeystorePassword`. Note changes to case on keystone and Pass to Password.

**Comment by kbareis** [comment]
Updated code and added in some additional sed / awks
